language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      # Cross compiler and cross compiled C libraries
      - gcc-multilib

script:
  - cargo build --verbose
  - cargo test --verbose
  - rustup target add i686-unknown-linux-gnu
  - cargo build --target=i686-unknown-linux-gnu --verbose
  - cargo test --target=i686-unknown-linux-gnu --verbose
  - cargo doc
