language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - rustup target add i686-unknown-linux-gnu
  - cargo build --target=i686-unknown-linux-gnu --verbose
  - cargo test --target=i686-unknown-linux-gnu --verbose
  - cargo doc
